// Test reset
POST http://localhost:8080/admin/reset

###
// Test valid chirp

POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "I had something interesting for breakfast",
  "userId": "066d38d9-f774-4889-b356-14a3e761d075"
}

###
// Test invalid (too long) chirp

POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
}

###
// Test invalid json

POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
    "notbody": "should fail"
}

###
// Test profane filter

POST http://localhost:8080/api/validate_chirp
Content-Type: application/json

{
  "body": "clean my dirty fornax mouth"
}

###
// Test new user

POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "someuser.email.com"
}

###
// Test get chirps

GET http://localhost:8080/api/chirps
Content-Type: application/json

###
// Test get chirp

GET http://localhost:8080/api/chirps/a06bdb00-7382-48a4-b21a-d37b1cb66909
Content-Type: application/json